source 'http://rubygems.org'

gem 'rails', '3.0.0.rc'

gem "tommy", :path => "../"

gem 'sqlite3-ruby', :require => 'sqlite3'
gem "ruby-debug"

gem "rspec-rails", ">= 2.0.0.beta.8", :group => [:test, :development]
gem 'capybara'
gem 'cucumber-rails'
gem 'cucumber', '>= 0.7.2'
gem 'spork'