source 'http://rubygems.org'

gem 'rails', '3.0.0.rc'

gem 'sqlite3-ruby', :require => 'sqlite3'
gem "ruby-debug"
gem 'inherited_resources' #this should be in tommy's gemfile - do later
gem "tommy", :path => "../"

